baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'サプリHACK'
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe = true
[params]
  mainSections = ["posts"]
[params]
  show_full_content = true